In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
df = pd.read_csv("/home/dell/ML-Learning/datasets/online_retail_II_cleaned.csv")

print("Shape of Dataset :", df.shape)

df.head()

Shape of Dataset : (1021452, 10)

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,is_cancelled,has_customer_id
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False,True
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,True
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,True
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False,True
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False,True

In [4]:
# Orders with quantity greater than or equal to 100 are considered bulk orders

df["is_bulk_order"] = 0

df.loc[df["quantity"] >= 100, "is_bulk_order"] = 1

df[["quantity","is_bulk_order"]].head()

print(df["is_bulk_order"].value_counts())

is_bulk_order
0    1008112
1      13340
Name: count, dtype: int64

In [ ]:

features = [
    "price",
    "country"
]

X = df[features]

y = df["is_bulk_order"]

print(X.head())

   price         country
0   6.95  United Kingdom
1   6.75  United Kingdom
2   6.75  United Kingdom
3   2.10  United Kingdom
4   1.25  United Kingdom

In [6]:
encoder = LabelEncoder()

X["country"] = encoder.fit_transform(X["country"])

X.head()

   price  country
0   6.95       40
1   6.75       40
2   6.75       40
3   2.10       40
4   1.25       40

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data :", X_train.shape)

print("Testing Data :", X_test.shape)

Training Data : (817161, 2)
Testing Data : (204291, 2)

In [8]:
scaler = StandardScaler()

X_train[["price"]] = scaler.fit_transform(X_train[["price"]])
X_test[["price"]] = scaler.transform(X_test[["price"]])

X_train.head()

           price  country
426656 -0.602614       40
875427 -0.351353       11
285748 -0.085793       40
698242  0.486183       40
382889  0.690460       40

In [9]:
model = LogisticRegression()

model.fit(X_train, y_train)

print("Model Trained Successfully")

Model Trained Successfully

In [11]:
pred = model.predict(X_test)

pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
accuracy = accuracy_score(y_test, pred)

print("Accuracy :", accuracy)

Accuracy : 0.9868667733771923

In [13]:
cm = confusion_matrix(y_test, pred)

print(cm)

[[201608      0]
 [  2683      0]]

In [14]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})

importance

   Feature  Coefficient
0    price    -2.843932
1  country    -0.038779